### ISSUE TITLE
Allow higher version in peerDependency of @astrojs/db

### ISSUE THREAD

**Issue by pReya** [pilcrowOnPaper/lucia-adapter-astrodb#12]
Currently, the adapter won't install, because the latest `@astrojs/db` version is `0.11`, which is out of the given range which gues to `0.10`. Can you increase the allowed range?

Thanks for your work!

**Comment by zellwk** [comment]
Having the same problem today. Was testing out Astro DB with Lucia, hope to be able to use this. 

![CleanShot 2024-05-29 at 14 25 07@2x](https://github.com/pilcrowOnPaper/lucia-adapter-astrodb/assets/3607637/9877b449-20db-4a91-93c7-af71e38a2422)

**Comment by pilcrowonpaper** [comment]
Super sorry about this, should be fixed with the latest version

**Comment by pReya** [comment]
@pilcrowOnPaper This happens again, since AstroDB has reached 0.13.0

```
npm warn Found: @astrojs/db@0.11.7
npm warn node_modules/@astrojs/db
npm warn   @astrojs/db@"^0.13.0" from the root project
npm warn   1 more (lucia-adapter-astrodb)
npm warn
npm warn Could not resolve dependency:
npm warn peer @astrojs/db@"0.8 - 0.11" from lucia-adapter-astrodb@0.0.9
npm warn node_modules/lucia-adapter-astrodb
npm warn   lucia-adapter-astrodb@"^0.0.9" from the root project
```
