### ISSUE TITLE
Astro DB no longer exports type Sqlitedb

### ISSUE THREAD

**Issue by OliverSpeir** [pilcrowOnPaper/lucia-adapter-astrodb#15]
Doesn’t break anything but figured it was worth noting

https://github.com/pilcrowOnPaper/lucia-adapter-astrodb/blob/ecefa40be925b877e4bdf22b833fae1ce601f2f2/src/index.ts#L4

Think this was changed in https://github.com/withastro/astro/pull/10457

Thanks so much for making this by the way, if you have an idea for how you want to do the type I could make a PR

**Comment by pilcrowonpaper** [comment]
I can't seem to find a type to replace it with so this might need an action from Astro's side. Trying to confirm this with the maintainers right now

**Comment by OliverSpeir** [comment]
Ok so https://github.com/withastro/astro/pull/11216 starts exporting the type again which should go out with `@astrojs/db@0.11.5`

Now the consideration is that the type has been (accurately) renamed to `Database` instead of `SqliteDB`

**Comment by pilcrowonpaper** [comment]
Thanks for making the PR!

**Comment by millette** [comment]
@pilcrowOnPaper I didn't see a PR here for this issue so I made #16.

I was a little bit confused since the git tag says 0.0.8 but the npm published version is 0.0.9.
